sudo: required
services:
 - docker

before_install:
 - docker build -t irfan/docker-react -f Dockerfile.dev .

script:
 - docker run irfan/docker-react npm run test -- --coverage

deploy:
 provider: elasticbeanstalk
 region: "us-east-1"
 app: "docker-react"
 env: "Dockerreact-env"
 bucket_name: "elasticbeanstalk-us-east-1-666990104785"
 bucket_path: "docker-react"
 on:
   branch: master
  access_key_id: $AWS_access_key
  secret_access_key:
   secure: "$AWS_secret_key"  